sudo: required
dist: trusty
language: python
python: # Only two versions for now
  - "2.7"
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
  - pip install -U scikit-image
  - pip install scipy
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl

script:
  - python Assignment-4/src/conv_net_relu.py
